

name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: sudo apt-get install nasm && sudo apt-get install gcc && sudo apt-get install gcc-multilib && make
     
